# Generated by Django 4.2.6 on 2023-10-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
